
package webs.student;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentScoreImpl", targetNamespace = "http://impl.web.learn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentScoreImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getScoreById", targetNamespace = "http://impl.web.learn/", className = "webs.student.GetScoreById")
    @ResponseWrapper(localName = "getScoreByIdResponse", targetNamespace = "http://impl.web.learn/", className = "webs.student.GetScoreByIdResponse")
    @Action(input = "http://impl.web.learn/StudentScoreImpl/getScoreByIdRequest", output = "http://impl.web.learn/StudentScoreImpl/getScoreByIdResponse")
    public String getScoreById(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
