
package webs.student;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentScoreImplService", targetNamespace = "http://impl.web.learn/", wsdlLocation = "http://127.0.0.1:3306/student?wsdl")
public class StudentScoreImplService
    extends Service
{

    private final static URL STUDENTSCOREIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTSCOREIMPLSERVICE_EXCEPTION;
    private final static QName STUDENTSCOREIMPLSERVICE_QNAME = new QName("http://impl.web.learn/", "StudentScoreImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:3306/student?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTSCOREIMPLSERVICE_WSDL_LOCATION = url;
        STUDENTSCOREIMPLSERVICE_EXCEPTION = e;
    }

    public StudentScoreImplService() {
        super(__getWsdlLocation(), STUDENTSCOREIMPLSERVICE_QNAME);
    }

    public StudentScoreImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTSCOREIMPLSERVICE_QNAME, features);
    }

    public StudentScoreImplService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTSCOREIMPLSERVICE_QNAME);
    }

    public StudentScoreImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTSCOREIMPLSERVICE_QNAME, features);
    }

    public StudentScoreImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentScoreImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentScoreImpl
     */
    @WebEndpoint(name = "StudentScoreImplPort")
    public StudentScoreImpl getStudentScoreImplPort() {
        return super.getPort(new QName("http://impl.web.learn/", "StudentScoreImplPort"), StudentScoreImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentScoreImpl
     */
    @WebEndpoint(name = "StudentScoreImplPort")
    public StudentScoreImpl getStudentScoreImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.web.learn/", "StudentScoreImplPort"), StudentScoreImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTSCOREIMPLSERVICE_EXCEPTION!= null) {
            throw STUDENTSCOREIMPLSERVICE_EXCEPTION;
        }
        return STUDENTSCOREIMPLSERVICE_WSDL_LOCATION;
    }

}
