package webservice.student.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.12
 * 2017-10-16T14:00:49.230+08:00
 * Generated source version: 3.0.12
 * 
 */
@WebService(targetNamespace = "http://impl.web.learn/", name = "StudentScoreImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface StudentScoreImpl {

    @WebMethod
    @Action(input = "http://impl.web.learn/StudentScoreImpl/getScoreByIdRequest", output = "http://impl.web.learn/StudentScoreImpl/getScoreByIdResponse")
    @RequestWrapper(localName = "getScoreById", targetNamespace = "http://impl.web.learn/", className = "webservice.student.wsdl.GetScoreById")
    @ResponseWrapper(localName = "getScoreByIdResponse", targetNamespace = "http://impl.web.learn/", className = "webservice.student.wsdl.GetScoreByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getScoreById(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
