package webservice.student.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.12
 * 2017-10-16T14:00:49.276+08:00
 * Generated source version: 3.0.12
 * 
 */
@WebServiceClient(name = "StudentScoreImplService", 
                  wsdlLocation = "http://127.0.0.1:3306/student?wsdl",
                  targetNamespace = "http://impl.web.learn/") 
public class StudentScoreImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.web.learn/", "StudentScoreImplService");
    public final static QName StudentScoreImplPort = new QName("http://impl.web.learn/", "StudentScoreImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:3306/student?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentScoreImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:3306/student?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentScoreImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentScoreImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentScoreImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StudentScoreImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StudentScoreImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StudentScoreImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns StudentScoreImpl
     */
    @WebEndpoint(name = "StudentScoreImplPort")
    public StudentScoreImpl getStudentScoreImplPort() {
        return super.getPort(StudentScoreImplPort, StudentScoreImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentScoreImpl
     */
    @WebEndpoint(name = "StudentScoreImplPort")
    public StudentScoreImpl getStudentScoreImplPort(WebServiceFeature... features) {
        return super.getPort(StudentScoreImplPort, StudentScoreImpl.class, features);
    }

}
